= Red Hat OpenShift AI Administration
:navtitle: Home

Welcome to this quick course on the _Red Hat OpenShift AI Administration_.
This course is the second in a series of 6 courses about Red Hat OpenShift AI:

1. https://redhatquickcourses.github.io/rhods-intro[Introduction to Red Hat OpenShift AI]
2. Red Hat OpenShift AI Administration  (_This course_)
3. Data Analysis and Visualization with Red Hat OpenShift AI (Under Development)
4. https://redhatquickcourses.github.io/rhods-model[Creating Machine Learning Models with Red Hat OpenShift AI]
5. https://redhatquickcourses.github.io/rhods-deploy[Deploying Machine Learning Models with Red Hat OpenShift AI]
6. https://redhatquickcourses.github.io/rhods-pipelines[Automation using Data Science Pipelines]

NOTE: After you have completed all the courses in the learning path, you can attempt the https://github.com/RedHatQuickCourses/rhods-qc-apps/tree/main/7.hands-on-lab["Workshop final hands-on lab"], that tests your understanding of the concepts taught in all the courses.

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Jiri Tesar
* Jaime Ramirez Castillo
* Max Murakami
* Trevor Royer
* John Hurlocker
* Ravi Srinivasan

== Classroom Environment

Use the https://demo.redhat.com/catalog?search=Red+Hat+OpenShift+Container+Platform+4.13+Workshop&item=babylon-catalog-prod%2Fopenshift-cnv.ocp413-wksp-cnv.prod[Red Hat OpenShift Container Platform 4.13 Workshop] catalog item from Red Hat Demo Platform (RHDP).

When ordering this demo item:

* Select at least two users in the `User Count` field.
Having two users is required for the user management exercise.

* In the `OpenShift worker memory size` field, select `64Gi`.
This size might be required if you run multiple workbenches and pipelines simultaneously.

[IMPORTANT]
====
RHOAI workbenches and pipelines use large container images.
Dependencies such as Tensorflow, PyTorch, or CUDA result in images sizes of several gigabytes.

The data ingestion and training stages can demand large amounts of memory and CPU/GPU resources.
Make sure that your worker nodes have enough memory to accomodate pods that consume dozens of GB.
====

This classroom does *NOT* have RHOAI pre-installed.
You install and configure a basic RHOAI instance, and then continue using this instance with other courses in the learning path.

== Prerequisites

* Basic knowledge of OpenShift (or Kubernetes) administration
* Building and deploying container images
* OpenShift User and Role administration
* Basic knowledge of AWS EC2 and S3 services

== Objectives

The overall objectives of this course include:

* Installing RedHat OpenShift AI using the web console and CLI
* Upgrading RedHat OpenShift AI components
* Managing RedHat OpenShift AI users and controlling access
* Enabling GPU support in RedHat OpenShift AI
* Stopping idle notebooks
* Create and configure a custom notebook image
