site:
  title: Red Hat OpenShift AI Administration
  start_page: rhods-admin::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true
    experimental: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui