= Building Custom Notebook Images

Custom notebook images allow you to add specific packages and libraries for your projects. This level of customization provides you with a consistent development environment for your teams to work in and ensures that your projects are reproducible between team members. You may also want to create custom notebooks that are more secure than the default notebook image provided in RHODS.

== Image source and Pre-built images

The default RHODS notebook images can be found in the https://github.com/opendatahub-io-contrib/workbench-images[opendatahub-io-contrib/workbench-images] repository. This repository contains the source code, pre-built images, and examples to help you create your own image. Workbench and runtime images are available.

*Workbench Images* +
These images can be used directly in workbenches within RHODS after importing them through the RHODS dashboard.

* Jupyter Data Science
* VSCode Data Science
* RStudio
* Jupyter PyTorch
* VSCode PyTorch
* Jupyter Tensorflow
* Jupyter Langchain
* Langflow 

*Runtime Images* +
These images can be used in Data Science Pipelines. They contain the exact same set of libraries as the above workbench images, except the IDE part.

* Runtime Data Science	
* Runtime Data Science (CUDA)	
* Runtime PyTorch (CUDA)	
* Runtime Tensorflow (CUDA)	
* Runtime R	
* Runtime Spark

For more information on OS packages, bundles, and IDE versions checkout the https://github.com/opendatahub-io-contrib/workbench-images#detailed-images-content[Detailed Images Content] section.

== Building your own images
We will now build our own image from one of the workbench images listed above.


=== Rules
* On OpenShift, every containers in a standard namespace (unless you modify security) run with a user with a random user id (uid), and the group id (gid) 0. Therefore, all the folders that you want to write in, and all the files you want to modify (temporarily) in your image must be accessible by this user. The *best practice* is to set the *ownership at 1001:0* (user "default", group "0").
* If you don't want/can't do that, another solution is to set permissions properly for any user, like 775.
* When launching a notebook from Applications->Enabled, the "personal" volume of a user is mounted at /opt/app-root/src. This is not configurable, so make sure to build your images with this default location for the data that you want persisted.

=== Requirements
* Need podman
* Need an image registry

=== Containerfile Overview
Below is the Containerfile that we'll use to create our custom notebook image.

Before you start to edit the Containerfile lets go over what this Containerfile is doing.

The FROM command contains the base image that we'll be using to build our custom image from. This will already contain common python packages that Data Scientists use.

[source,dockerfile]
----
FROM quay.io/opendatahub-contrib/workbench-images:jupyter-datascience-c9s-py311_2023c_latest
----

The COPY command copies a requirements.txt file with the extra pacakge that we will need in our notebook. The only package we're installing is Seaborn which is a Python data visualization library. Multiple packages can be installed with the requirements.txt file.

[source,dockerfile]
----
COPY requirements.txt ./
----

The next step is to install the package.
[source,dockerfile]
----
RUN echo "Installing softwares and packages" && \
    pip install micropipenv && \
    # Install Python packages \
    micropipenv install && \
    rm -f ./requiremnents.txt
----

We're printing out where Java is installed. Since we haven't installed it yet and it's not part of our base image we should expect the output to be blank.
[source,dockerfile]
----
RUN echo "-- WHERE IS JAVA= " && whereis java
----

Now we'll install OpenJDK. Note that we are switching to the root user (User 0). We need to do this to have the appropriate permissions to install OpenJDK. After the isntallation command is completed we switch back to User 1001 since the root user is not allowed to run containers in OpenShift.
[source,dockerfile]
----
USER 0

RUN INSTALL_PKGS="java-11-openjdk java-11-openjdk-devel" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    yum -y clean all --enablerepo='*'

USER 1001
----

Now we should be able to see where Java is installed.
[source,dockerfile]
----
RUN echo "-- WHERE IS JAVA= " && whereis java && python -V
----

Lastly, we'll fix the permissons to support pip in OpenShift, set the work directory, and entry point for the container.
[source,dockerfile]
----
RUN chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P

WORKDIR /opt/app-root/src

ENTRYPOINT ["start-notebook.sh"]
----

=== Build Steps (TODO: Get screenshots of below steps)
1. Copy code and open in VSCode.
2. Open the requirements.txt file + 
   Note the Seborn dependency in the file.
3. Open the Containerfile
4. Add the appropriate commands in the TODO sections. Refer to the Containerfile Overview section above.
5. We'll now build the image with podman. Open a terminal and got to the root directory where you copied the code. Run the below command. +
podman build -t rhods-custom-image .
6. Push the image to your quay repository.

Now you're ready to import the image into RHODS! See the next section to learn how to import your custom image and test it out.


