= Managing Resources

=== Manually Creating Data Science Projects

When self-provisioner is disabled on a cluster, a cluster administrator will be required to manually create Data Science Projects for users.

As mentioned previously, a Data Science Project is a normal OpenShift project/namespace with a few special labels that allow to to be managed by the RHODS Dashboard, allowing it to be managed using any existing processes or tools your organization already utilizes to manage namespaces.

To manually create a Data Science Project from the cli, you can run the following commands to create a namespace and apply the necessary labels:

```sh
oc create namespace myproject
oc label namespace myproject opendatahub.io/dashboard='true' modelmesh-enabled='true' 
```

Alternatively, the following YAML object can be used to create the Data Science Project:

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: myproject
  labels:
    modelmesh-enabled: 'true'
    opendatahub.io/dashboard: 'true'
```

Once the Data Science Project has been created, access to the project will need to be configured for the necessary user or group using either the cli, or a namespace RoleBinding.  Refer to the OpenShift documentation for https://docs.openshift.com/container-platform/4.13/authentication/using-rbac.html#adding-roles_using-rbac[Adding roles to users] for additional instructions.


== Notes
* What kind of resources are created in a RHODS DS project/workbench
* How to control resource allocation - CPU, Storage and other resources
* How to clean up after a user is removed from the group and from RHODS
* Idle culler configuration - free up resources and kill idle notebooks
* Enabling and configuring GPUs for workload acceleration
* Why is GPU acceleration beneficial and how to configure it
* How to provision for certain groups of users and not all


