= Installation of Red{nbsp}Hat OpenShift AI

== Supported configurations
OpenShift AI is supported in two configurations:
 
 * A managed cloud service add-on for *Red Hat OpenShift Dedicated* (with a Customer Cloud Subscription for AWS or GCP) or for Red Hat OpenShift Service on Amazon Web Services (ROSA).
For information about OpenShift AI on a Red Hat managed environment, see https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_cloud_service/1[Product Documentation for Red Hat OpenShift AI Cloud Service 1]

* Self-managed software that you can install on-premise or on the public cloud in a self-managed environment, such as *OpenShift Container Platform*.
For information about OpenShift AI as self-managed software on your OpenShift cluster in a connected or a disconnected environment, see https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.9[Product Documentation for Red Hat OpenShift AI Self-Managed 2.9]

In this course we cover installation of *Red Hat OpenShift AI self-managed* using the OpenShift Web Console.
