= General Information about Installation   

Red{nbsp}Hat OpenShift Data Science is available to install a self-managed version as an operator through OperatorHub or as a fully managed solution through OpenShift Marketplace. 

In addition to the *Red{nbsp}Hat OpenShift Data Science* Operator there are some other operators that you may need to install depending on which features and components of *Red{nbsp}Hat OpenShift Data Science* you want to install and use.

https://www.redhat.com/en/technologies/cloud-computing/openshift/pipelines[Red{nbsp}Hat OpenShift Pipelines Operator]::
The *Red{nbsp}Hat OpenShift Pipelines Operator* is required if you want to install the  *Red{nbsp}Hat OpenShift Data Science Pipelines* component.

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/index.html[NVIDIA GPU Operator]::
The *NVIDIA GPU Operator* is required for GPU support in  Red Hat OpenShift Data Science.

https://docs.openshift.com/container-platform/4.13/hardware_enablement/psap-node-feature-discovery-operator.html[Node Feature Discovery Operator]::
The *Node Feature Discovery Operator* is a prerequisite for the *NVIDIA GPU Operator*.
