= General Information about Installation   

Red{nbsp}Hat OpenShift AI is available to install as an operator through the *OperatorHub*, or as a fully managed solution through the OpenShift Marketplace.

[INFO]
====
The product name has been recently changed to *Red{nbsp}Hat OpenShift AI (RHOAI)* (old name *Red{nbsp}Hat OpenShift Data Science*). In this course, most references to the product use the new name. However, references to some UI elements might still use the previous name.
====

In addition to the *Red{nbsp}Hat OpenShift AI* Operator there are some other operators that you may need to install depending on which features and components of *Red{nbsp}Hat OpenShift AI* you want to install and use. 

https://www.redhat.com/en/technologies/cloud-computing/openshift/serverless[Red{nbsp}Hat OpenShift Serverless Operator]::
The *Red Hat OpenShift Serverless operator* provides a collection of APIs that enables containers, microservices and functions to run "serverless". The *Red{nbsp}Hat OpenShift Serverless Operator* is required if you want to install the single-model serving platform component.

https://catalog.redhat.com/software/container-stacks/detail/5ec53e8c110f56bd24f2ddc4[Red{nbsp}Hat OpenShift Service Mesh Operator]::
*Red Hat OpenShift Service Mesh operator* provides an easy way to create a network of deployed services that provides discovery, load balancing, service-to-service authentication, failure recovery, metrics, and monitoring. The *Red{nbsp}Hat OpenShift Serverless Operator* is required if you want to install the single-model serving platform component.

https://developers.redhat.com/articles/2021/06/18/authorino-making-open-source-cloud-native-api-security-simple-and-flexible[Red{nbsp}Hat Authorino (technical preview) Operator]::
*Red Hat Authorino* is an open source, Kubernetes-native external authorization service to protect APIs. The *Red{nbsp}Hat Authorino Operator* is required to support enforcing authentication policies in Red Hat OpenShift AI.

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/index.html[NVIDIA GPU Operator]::
The *NVIDIA GPU Operator* is required for GPU support in  Red Hat OpenShift AI.

https://docs.openshift.com/container-platform/latest/hardware_enablement/psap-node-feature-discovery-operator.html[Node Feature Discovery Operator]::
The *Node Feature Discovery Operator* is a prerequisite for the *NVIDIA GPU Operator*.


[IMPORTANT]
====
Make sure that the https://access.redhat.com/solutions/6993520[internal OpenShift image registry] is running before installing and running RHOAI.

RHOAI uses the internal image registry to pull prebuilt notebook images that are used to run containerized workbenches.
====
