//find a better title
= General Information about Installation   

The *Red{nbsp}Hat Openshift Data Science* is distributed as an Openshift operator and available through the OpenShift marketplace. There are some other operators that you may need to install depending on which features and components of the *Red{nbsp}Hat Openshift Data Science* you want to install and use.

https://www.redhat.com/en/technologies/cloud-computing/openshift/pipelines[Red{nbsp}Hat Openshift Pipelines Operator]::
 This operator is required if you want to install the  *Red{nbsp}Hat Openshift Data Science Pipelines* component.

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/index.html[NVIDIA GPU Operator]::
https://docs.openshift.com/container-platform/4.13/hardware_enablement/psap-node-feature-discovery-operator.html[Node Feature Discovery Operator]::
The *NVIDIA GPU Operator* is necessary when you want to https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1.33/html-single/installing_openshift_data_science_self-managed/index#enabling-gpu-support-in-openshift-data-science_install[enable graphics processing units (GPUs)] in *Openshift Data Science* to ensure that data scientists can use compute-heavy workloads. 
The *Node Feature Discovery Operator* is a prerequisity for the *NVIDIA GPU Operator*.

[IMPORTANT]
*Red{nbsp}Hat Openshift Data Science* operator is available in two different main versions at the moment - *Red{nbsp}Hat Openshift Data Science Operator V1* and *Red{nbsp}Hat Openshift Data Science operator V2*. There are some differences in installation between the two. Mainly that the V1 operator installs all the *Red{nbsp}Hat Openshift Data Science* components automatically whereas the V2 operator requires you to make a selection of the components to be installed and managed by the operator after the installation. In the class we focus on the V2 operator as it will become the stable version soon. At the moment it is available through the _alpha_ channel.
