= Installation Using the Command Line Interface

Similarly to the Web Console installation, both *Red{nbsp}Hat Openshift Pipelines* operator and *Red{nbsp}Hat Openshift Data Science* operators have to be installed.

== Introduction to CLI-based operator installations
In OpenShift, the Operator Lifecycle Manager (OLM) helps users install and manage operators and their associated services.
Operator Lifecycle Manager (OLM) uses following resources:

Catalog Resource::
  Each catalog source resource references an operator repository. Periodically, the OLM
  examines the catalog sources in the cluster and retrieves information about the operators in
  each source.

Package manifest::
 The OLM creates a package manifest for each available operator. The package manifest
 contains the required information to install an operator, such as the available channels.

Operator group::
  Operator groups define how the OLM presents operators across namespaces.
Subscription::
  Cluster administrators create subscriptions to install operators.
Operator::
  The OLM creates operator resources to store information about installed operators. 
Install plan::
  The OLM creates install plan resources as part of the installation and update process. When
  requiring approvals, administrators must approve install plans.
Cluster service version (CSV)::
  Each version of an operator has a corresponding CSV. The CSV contains the information that
  the OLM requires to install the operator.

When installing an operator, an administrator must create only the operator group (unless the target namespace is *openshift-operators* where the operator group resource already exists) and the subscription. Optionally a namespace can be created if it does not exists.

Following are examples of the resources an adminstrator must create.

Namespace::
--
[subs=+quotes]
----
apiVersion: v1
kind: Namespace
metadata:
  name: _operator_namespace_ <1>
spec: {}
----
<1> Name of the namespace to install the operator into.
--
NOTE: Namespace has to be only created if it does not already exist. An operator can be installed into an existing namespace.

Operator group::
--
[subs=+quotes]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: _Operator_group_name_ <1>
  namespace: _operator_namespace_ <2>
spec: {}
----
<1> Name of the operator group resource.
<2> Name of the namespace to create the operator group resource in.
--

Subscription::
--
[subs=+quotes]
[#subscription]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: _Subscription_name_  <1>
  namespace: _operator_namespace_ <2>
spec:
  channel: _channel_ <3>
  installPlanApproval: _Manual/Automatic_ <4>
  name: _Operator_name_
  source: _Catalog_source_
  sourceNamespace: openshift-marketplace
  startingCSV: _Operator_CSV_ <5>
----
<1> Name of the subscription resource.
<2> Name of the namespace to create the subscription resource in.
<3> Update channel to install the operator from. For more information about finding available channels see this xref:section3.adoc#findchannel[note].
<4> installPlanApproval can be either *Automatic* or *Manual*.
<5> Staring Cluster Service Version of the operator. For more information about finding available CSVs see this xref:section3.adoc#findchannel[note].

--

[#manual_approval]
IMPORTANT: When *installPlanApproval* is set to  *Manual*, the installation has to be manually approved in order to start.

--
[subs=+quotes]
----
$ *oc get installplan -n _operator_namespace_*
NAME            CSV                     APPROVAL   APPROVED
install-vpgls   _operator_csv_   Manual     #false#   <1>

$ *oc patch installplan install-vpgls --type merge -p '{"spec":{"approved":true}}' -n _operator_namespace_*
installplan.operators.coreos.com/install-vpgls patched  <2>

$ *oc get installplan -n redhat-ods-operator*
NAME            CSV                     APPROVAL   APPROVED
install-vpgls   _operator_name_   Manual     #true#  <3>
----
<1> Approval has not been set.
<2> The patch command approves the installation.
<3> Approval has been set and installation starts.
--

--
[#findchannel]
NOTE: It can be little challenging to find available channels and their Cluster Service Versions (CSVs) from the CLI. _JQuery_ is a powerfull tool to filter values from resource manifests.

The following example lists available channels for the *rhods-operator* operator.
[subs=+quotes]
----
*$ oc get packagemanifest rhods-operator -o json|jq '.status.channels[].name'*
"beta"
"embedded"
"stable"
"alpha"
----

To find available CSVs for a particular channel you can use the following command.

[subs=+quotes]
----
*$ oc get packagemanifest rhods-operator -o json| \
  jq '.status.channels[]|select(.name=="#alpha#").entries'* <1>
  [
  {
    "name": "rhods-operator.2.2.0",   <2>
    "version": "2.2.0"
  },
  {
    "name": "rhods-operator.2.1.0",
    "version": "2.1.0"
  }
]
----
<1> *alpha* is the name of the channel.
<2> The value of the _name_ attribute is used as a value of the xref:section3.adoc#subscription[startingCSV] attribute in the subscription to select the starting channel.
--

== Installation of the Red{nbsp}Hat Openshift Data Science operator

1. Red{nbsp}Hat Openshift Data Science operator is available through Red Hat Operators catalogue.
+
[subs=+quotes]
----
$ *oc get packagemanifest | grep rhods-operator*
rhods-operator                                     Red Hat Operators     3h34m
----

2. The operator has a suggested namespace *redhat-ods-operator* to be installed into. However it can be installed into any namespace you choose.
+
[subs=+quotes]
----
$ *oc describe packagemanifest rhods-operator*
_...output ommited..._
operatorframework.io/suggested-namespace:  redhat-ods-operator
_...output ommited..._
----

3. Unless you choose to install it into the _openshift-operators_ namespace, create the namespace first.
+
--
[subs=+quotes]
----
$ *cat <<EOF > rhods-ns.yaml*
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
spec: {}
EOF

$ *oc create -f rhods-ns.yaml*
namespace/redhat-ods-operator created
----
--

4. Within the new namespace create the  *Operator Group* resource.
+
[subs=+quotes]
----
$ *cat <<EOF > rhods-og.yaml*
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-ods-operator
  namespace: redhat-ods-operator
spec: {}
EOF

$ *oc create -f rhods-og.yaml*
operatorgroup.operators.coreos.com/redhat-ods-operator created
----

5. Finally create the  operator's subscription to start the installation.
+
--
[subs=+quotes]
----
$ *cat <<EOF > rhods-subs.yaml*
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhods-operator.2.2.0
EOF

$ *oc create -f rhods-subs.yaml*
subscription.operators.coreos.com/rhods-operator created
----


[NOTE]
In case the *installPlanApproval* is set to *Manual*, approve the installation first to start it. Refer to the xref:section3.adoc#manual_approval[previous section] for more information.
--

6. Create your Openshift DataScience Cluster
+
----
cat <<EOF > rhods-cluster.yaml
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  labels:
    app.kubernetes.io/created-by: rhods-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: rhods-operator
  name: mycluster
spec:
  components:
    codeflare:
      managementState: Removed
    dashboard:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    kserve:
      managementState: Removed
    modelmeshserving:
      managementState: Managed
    ray:
      managementState: Removed
    workbenches:
      managementState: Managed
EOF

oc create -f rhods-cluster.yaml
----

[NOTE]
It may take some time for all the operator's pods to start hence the *Red{nbsp}Hat Openshift Data Science* dashboard may not be available immediately. You can check their status in the *redhat-ods-applications* namespace. Once all pods are running and ready, you can open the dashboard in the Openshift Web Console.

[subs=+quotes]
----
$ *oc get pods -n redhat-ods-applications*
NAME                                               READY   STATUS              RESTARTS   AGE
etcd-cc4d875c-8trld                                0/1     PodInitializing     0          7s
modelmesh-controller-5749b94578-2j8nv              0/1     Running             0          7s
modelmesh-controller-5749b94578-jcxc7              0/1     ContainerCreating   0          7s
modelmesh-controller-5749b94578-rww94              0/1     ContainerCreating   0          7s
notebook-controller-deployment-685bb8f9d6-6dtbh    0/1     Running             0          29s
odh-model-controller-7d495b56cb-8pnn9              0/1     Running             0          7s
odh-model-controller-7d495b56cb-8xh5h              0/1     Running             0          7s
odh-model-controller-7d495b56cb-kcmqr              0/1     Running             0          7s
odh-notebook-controller-manager-866b7cf859-2wf2j   1/1     Running             0          29s
rhods-dashboard-7bd94f464f-7lvn8                   1/2     Running             0          47s
rhods-dashboard-7bd94f464f-hksf6                   1/2     Running             0          47s
rhods-dashboard-7bd94f464f-n5rbz                   1/2     Running             0          47s
rhods-dashboard-7bd94f464f-pg984                   1/2     Running             0          47s
rhods-dashboard-7bd94f464f-xd255                   1/2     Running             0          47s
----

== Installation of other operators required by Openshift Data Science

You may need to install other operators depending on the components and features of Openshift Data Science you want to use:

* Red Hat Openshift Pipelines operator
* NVIDIA GPU Operator
* Node Feature Discovery Operator

The following exercise shows installation of the Red Hat Openshift Pipelines operator. Installation of the two other operators is very similar.



1. To install the *Red{nbsp}Hat Openshift Pipelines* operator, locate the `openshift-pipelines-operator-rh` package manifest.
+
[subs=+quotes]
----
$ *oc get packagemanifest | grep pipelines*
openshift-pipelines-operator-rh                    Red Hat Operators     24h
----

2. To get more information about the operator use *oc describe*. You need to find available channels and CSVs associated with them so you can use them later when creating the operator's subscription.
+
[subs=+quotes]
----
$ *oc describe packagemanifest openshift-pipelines-operator-rh -n openshift-marketplace*
Name:         openshift-pipelines-operator-rh
Namespace:    openshift-marketplace
Labels:       catalog=redhat-operators
..._output omitted_...
Spec:
Status:
  Catalog Source:               redhat-operators
  Catalog Source Display Name:  Red Hat Operators
  Catalog Source Namespace:     openshift-marketplace
  Catalog Source Publisher:     Red Hat
  Channels:
    Current CSV:  openshift-pipelines-operator-rh.v1.12.0
    Current CSV Desc:
      Annotations:
        Alm - Examples:  [
..._output omitted_...
----


3. The Pipelines operator's default namespace is _openshift-operators_, hence neither the namespace nor operator group resources must be created. Create only the subscription resource to start the installation. Following is an example of the Pipelines operator subscription creation.
+
--
[subs=+quotes]
----
$ *cat <<EOF > pipelines-subs.yaml*
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator-rh.v1.12.0
EOF

$ *oc create -f pipelines-subs.yaml*
----


[NOTE]
In case *installPlanApproval* is set to *Manual*, approve the installation first to start it. Refer to the xref:section3.adoc#manual_approval[previous section] for more information.
--
